create table if not exists public.users (
  id bigint generated by default as identity primary key,
  email text not null unique,
  password text not null,
  created_at timestamptz not null default now()
);

create table if not exists public.portfolio_items (
  id bigint generated by default as identity primary key,
  user_id bigint not null references public.users(id) on delete cascade,
  category text not null check (category in ('owned', 'watchlist', 'wishlist')),
  symbol text not null,
  company_name text,
  shares numeric,
  avg_price numeric,
  target_price numeric,
  note text,
  created_at timestamptz not null default now()
);

create index if not exists portfolio_items_user_id_idx
  on public.portfolio_items (user_id);

create index if not exists portfolio_items_user_category_idx
  on public.portfolio_items (user_id, category);